apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox
resources:
  - deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: metrics-configmap
    files:
      - metrics.txt
