apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phlare
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: phlare
    targetRevision: 0.4.0
  destination:
    server: https://kubernetes.default.svc
    namespace: phlare
