apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.3.1
    helm:
      version: v3
      parameters:
        - name: service.clusterIP
          value: "10.96.0.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
