{
 "title": "Argo CD Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Reconcile Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(argocd_app_reconcile_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(argocd_app_reconcile_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"argocd\",container=\"application-controller\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"argocd\",container=\"application-controller\"} / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync duration",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=~\"argocd/argocd-application-controller\"} | logfmt | msg =\"Reconciliation completed\" | line_format \"{{.time}} {{.application}}: {{.time_ms}}ms\""
    }
   ]
  },
  {
   "title": "Sync Trigger",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=~\"argocd/argocd-application-controller\"} | logfmt | level = \"debug\" msg =~ \"Refreshing app .*\" |  line_format \"{{.time}} {{.msg}}\""
    }
   ]
  },
  {
   "title": "Flame Graph",
   "type": "flamegraph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "labelSelector": "{namespace=\"argocd\",pod=\"argocd-application-controller-0\"}",
     "profileTypeId": "goroutine:goroutine:count:goroutine:count"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "serviceName": "argocd-controller" }
   ]
  }
 ]
}