apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata: # kpt-merge: /cert-manager
  name: cert-manager
  annotations:
    config.kubernetes.io/local-config: "true"
    argocd.argoproj.io/hook: Skip
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|RenderHelmChart|default|cert-manager'
helmCharts:
- chartArgs:
    name: cert-manager
    version: v1.15.3
    repo: https://charts.jetstack.io
  templateOptions:
    releaseName: cert-managerr
    namespace: cert-manager
    values:
      valuesInline:
        crds:
          enabled: true
