apiVersion: v1
kind: Pod
metadata:
  name: request
  labels:
    app.kubernetes.io/name: request
spec:
  containers:
    - name: request
      image: ghcr.io/cybozu/ubuntu-debug:24.04
      command: [ "/bin/bash" ]
      args: ["-c", "while true; do curl -s http://todo/test; sleep 1; done"]
