apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: todo
  name: todo
spec:
  type: ClusterIP
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: todo
