apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: victoriametrics
spec:
  discoveryRole: service
  namespaceSelector:
    matchNames: [kube-system]
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
  - honorLabels: true
    port: http-metrics
    relabelConfigs:
      - action: labelkeep
        regex: __.*
      - replacement: kube-state-metrics
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kube-state-metrics-telemetry
  namespace: victoriametrics
spec:
  namespaceSelector:
    matchNames: [kube-system]
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  podMetricsEndpoints:
  - port: telemetry
    relabelConfigs:
      - replacement: kube-state-metrics-telemetry
        targetLabel: job
