apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-exporter
  namespace: victoriametrics
spec:
  namespaceSelector:
    matchNames: [kube-system]
  selector: {}
  endpoints:
  - relabelConfigs:
      - replacement: node-exporter
        targetLabel: job
      - sourceLabels: [__meta_kubernetes_endpoints_name]
        action: keep
        regex: node-exporter-prometheus-node-exporter
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}
        target_label: address
