apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: victoriametrics
  namespace: grafana
spec:
  name: middleware.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://vmsingle-database.victoriametrics:8429
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki
  namespace: grafana
spec:
  name: loki.yaml
  datasources:
    - name: loki
      type: loki
      access: proxy
      url: http://loki.loki.svc:3100
      version: 1
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
