apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - podmonitor.yaml
  - promlens.yaml
  - vmagent.yaml
  - vmsingle.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
configMapGenerator:
  - name: grafana-dashboards
    files:
      - ./dashboards/argocd-performance.json
