apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: todo
  namespace: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - sandbox
  selector:
    matchLabels:
      app.kubernetes.io/name: todo
  podMetricsEndpoints:
    - port: http
      scheme: http
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dummy-metrics
  namespace: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - sandbox
  selector:
    matchLabels:
      app.kubernetes.io/name: dummy-metrics
  podMetricsEndpoints:
    - port: http
      scheme: http
      path: /metrics
