apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/name: argocd-metrics
  endpoints:
    - port: metrics
      relabelings:
        - replacement: argocd
          targetLabel: job
        - sourceLabels: [ __meta_kubernetes_service_name ]
          action: keep
          regex: argocd-metrics
