apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zoetrope/k8s-hands-on.git
    targetRevision: main
    path: manifests/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: default
