# Source: cert-manager/templates/webhook-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-managerr-webhook
  namespace: cert-manager
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-managerr
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.15.3"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.15.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/instance: cert-managerr
      app.kubernetes.io/component: "webhook"
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/name: webhook
        app.kubernetes.io/instance: cert-managerr
        app.kubernetes.io/component: "webhook"
        app.kubernetes.io/version: "v1.15.3"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: cert-manager-v1.15.3
    spec:
      serviceAccountName: cert-managerr-webhook
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cert-manager-webhook
        image: "quay.io/jetstack/cert-manager-webhook:v1.15.3"
        imagePullPolicy: IfNotPresent
        args:
        - --v=2
        - --secure-port=10250
        - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
        - --dynamic-serving-ca-secret-name=cert-managerr-webhook-ca
        - --dynamic-serving-dns-names=cert-managerr-webhook
        - --dynamic-serving-dns-names=cert-managerr-webhook.$(POD_NAMESPACE)
        - --dynamic-serving-dns-names=cert-managerr-webhook.$(POD_NAMESPACE).svc
        ports:
        - name: https
          protocol: TCP
          containerPort: 10250
        - name: healthcheck
          protocol: TCP
          containerPort: 6080
        livenessProbe:
          httpGet:
            path: /livez
            port: 6080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 6080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      nodeSelector:
        kubernetes.io/os: linux
