# Source: cert-manager/templates/webhook-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-managerr-webhook:dynamic-serving
  namespace: cert-manager
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-managerr
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.15.3"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.15.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-managerr-webhook:dynamic-serving
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-managerr-webhook
  namespace: cert-manager
