apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: sandbox-agent
  namespace: sandbox
spec:
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-database.victoriametrics.svc:8429/api/v1/write"
  podScrapeNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: sandbox
  scrapeInterval: 30s
