# Source: cert-manager/templates/cainjector-rbac.yaml
# grant cert-manager permission to manage the leaderelection configmap in the
# leader election namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-managerr-cainjector:leaderelection
  namespace: kube-system
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: cert-managerr
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/version: "v1.15.3"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.15.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-managerr-cainjector:leaderelection
subjects:
- kind: ServiceAccount
  name: cert-managerr-cainjector
  namespace: cert-manager
