name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
env:
  go-version: 1.19
jobs:
  sync:
    name: Sync all applications
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - run: go install github.com/yusukebe/t/cmd/t@latest
      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v1.38.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make launch-k8s
      - run: make deploy-argocd
      - name: patch targetRevision
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            BRANCH_NAME=${GITHUB_HEAD_REF}
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          fi
          echo change targetRevision to ${BRANCH_NAME}
          for app in namespaces monitoring sandbox; do
            kubectl patch -n argocd applications $app --type=json -p="[{'op':'replace','path':'/spec/source/targetRevision','value':${BRANCH_NAME}}]"
          done
      - run: make sync-applications
      - name: check status
        run: |
          IFS=$'\n'; for item in $(kubectl get app -n argocd -o json | jq -c '.items[]'); do
            echo $item | jq -r .metadata.name
            echo $item | jq -r .status.health.status | t Healthy
            echo $item | jq -r .status.sync.status | t Synced
          done
